# Stage 1: Build de l'app React
FROM node:18 AS build

WORKDIR /app

# Déclarer les agrguments de build
ARG REACT_APP_API_KEY
# Pour le mode batch
ARG REACT_APP_MAXSIZEAUDIOBATCH
ARG REACT_APP_MAXTIMEPROCESSINGBATCH
ARG REACT_APP_TIMEBETTWENEACHPOLLINGBATCH
# Pour le mode diarization
ARG REACT_APP_MAXSIZEAUDIODIARIZATION
ARG REACT_APP_MAXTIMEPROCESSINGDIARIZATION
ARG REACT_APP_TIMEBETWEENEACHPOLLINGDIARIZATION
ARG REACT_APP_MAXSPEAKERSDIARIZATION

# Les transformer en variables d'environnement avant le build
ENV REACT_APP_API_KEY=$REACT_APP_API_KEY
# Pour le mode batch
ENV REACT_APP_MAXSIZEAUDIOBATCH=$FRONTEND_MAX_AUDIO_SIZE_BATCH
ENV REACT_APP_MAXTIMEPROCESSINGBATCH=$FRONTEND_MAX_TIME_PROCESSING_BATCH
ENV REACT_APP_TIMEBETTWENEACHPOLLINGBATCH=$FRONTEND_TIME_BETWEEN_EACH_POLLING_BATCH
# Pour le mode diarization
ENV REACT_APP_MAXSIZEAUDIODIARIZATION=$FRONTEND_MAX_AUDIO_SIZE_DIARIZATION
ENV REACT_APP_MAXTIMEPROCESSINGDIARIZATION=$FRONTEND_MAX_TIME_PROCESSING_DIARIZATION
ENV REACT_APP_TIMEBETWEENEACHPOLLINGDIARIZATION=$FRONTEND_TIME_BETWEEN_EACH_POLLING_DIARIZATION
ENV REACT_APP_MAXSPEAKERSDIARIZATION=$FRONTEND_MAX_SPEAKERS_DIARIZATION

COPY package.json package-lock.json ./

RUN npm install

COPY . .

WORKDIR /app

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# On supprime la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# On copie notre config personnalisée
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80