# Stage 1: Build de l'app React
FROM node:18 AS build

WORKDIR /app

# Déclarer les agrguments de build
ARG REACT_APP_API_KEY
# Pour le mode batch
ARG REACT_APP_MAX_SIZE_AUDIO_BATCH
ARG REACT_APP_MAX_TIME_PROCESSING_BATCH
ARG REACT_APP_TIME_BETWEEN_EACH_POLLING_BATCH
# Pour le mode diarization
ARG REACT_APP_MAX_SIZE_AUDIO_DIARIZATION
ARG REACT_APP_MAX_TIME_PROCESSING_DIARIZATION
ARG REACT_APP_TIME_BETWEEN_EACH_POLLING_DIARIZATION
ARG REACT_APP_MAX_SPEAKERS_DIARIZATION

# Les transformer en variables d'environnement avant le build
ENV REACT_APP_API_KEY=$REACT_APP_API_KEY
# Pour le mode batch
ENV FRONTEND_MAX_AUDIO_SIZE_BATCH=$REACT_APP_MAX_SIZE_AUDIO_BATCH
ENV FRONTEND_MAX_TIME_PROCESSING_BATCH=$REACT_APP_MAX_TIME_PROCESSING_BATCH
ENV FRONTEND_TIME_BETWEEN_EACH_POLLING_BATCH=$REACT_APP_TIME_BETWEEN_EACH_POLLING_BATCH
# Pour le mode diarization
ENV FRONTEND_MAX_AUDIO_SIZE_DIARIZATION=$REACT_APP_MAX_SIZE_AUDIO_DIARIZATION
ENV FRONTEND_MAX_TIME_PROCESSING_DIARIZATION=$REACT_APP_MAX_TIME_PROCESSING_DIARIZATION
ENV FRONTEND_TIME_BETWEEN_EACH_POLLING_DIARIZATION=$REACT_APP_TIME_BETWEEN_EACH_POLLING_DIARIZATION
ENV FRONTEND_MAX_SPEAKERS_DIARIZATION=$REACT_APP_MAX_SPEAKERS_DIARIZATION

COPY package.json package-lock.json ./

RUN npm install

COPY . .

WORKDIR /app

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# On supprime la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# On copie notre config personnalisée
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80