export const BatchTranscriptionEnv = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAXSIZEAUDIO: process.env.FRONTEND_MAX_AUDIO_SIZE_BATCH,
    MAXTIMEPROCESSING: process.env.FRONTEND_MAX_TIME_PROCESSING_BATCH, 
    TIMEBETTWENEACHPOLLING: process.env.FRONTEND_TIME_BETWEEN_EACH_POLLING_BATCH,
};

export const DiarizationEnv = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAXSIZEAUDIO: process.env.FRONTEND_MAX_AUDIO_SIZE_DIARIZATION,
    MAXTIMEPROCESSING: process.env.FRONTEND_MAX_TIME_PROCESSING_DIARIZATION, 
    TIMEBETTWENEACHPOLLING: process.env.FRONTEND_TIME_BETWEEN_EACH_POLLING_DIARIZATION,
    MAXSPEAKERS: process.env.FRONTEND_MAX_SPEAKERS_DIARIZATION,
};