export const BatchTranscriptionEnv = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAXSIZEAUDIO: process.env.REACT_APP_MAXSIZEAUDIOBATCH,
    MAXTIMEPROCESSING: process.env.REACT_APP_MAXTIMEPROCESSINGBATCH, 
    TIMEBETTWENEACHPOLLING: process.env.REACT_APP_TIMEBETTWENEACHPOLLINGBATCH,
};

export const DiarizationEnv = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAXSIZEAUDIO: process.env.REACT_APP_MAXSIZEAUDIODIARIZATION,
    MAXTIMEPROCESSING: process.env.REACT_APP_MAXTIMEPROCESSINGDIARIZATION, 
    TIMEBETTWENEACHPOLLING: process.env.REACT_APP_TIMEBETTWENEACHPOLLINGDIARIZATION,
    MAXSPEAKERS: process.env.REACT_APP_MAXSPEAKERS,
};