export const env = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAXSIZEBYTES: process.env.REACT_APP_MAXSIZEBYTES,
    MAXTIMEPROCESSING: process.env.REACT_APP_MAXTIMEPROCESSING, 
    TIMEBETTWENEACHPOLLING: process.env.REACT_APP_TIMEBETTWENEACHPOLLING,
};